name: Deploy static snapshot to gh-pages

on:
  push:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations and collectstatic
        env:
          DJANGO_SETTINGS_MODULE: myshop.settings
        run: |
          python manage.py migrate --noinput || true
          python manage.py collectstatic --noinput

      - name: Start Django dev server in background
        env:
          DJANGO_SETTINGS_MODULE: myshop.settings
        run: |
          nohup python manage.py runserver 0.0.0.0:8000 &
          sleep 2

      - name: Mirror site with wget
        run: |
          rm -rf export
          mkdir -p export
          wget --mirror --convert-links --adjust-extension --page-requisites --no-parent --directory-prefix=export http://127.0.0.1:8000/

      - name: Stop any python processes (best-effort)
        run: |
          pkill -f 'manage.py runserver' || true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./export/127.0.0.1:8000
          publish_branch: gh-pages
